include_cookbook 'symboliclinks'
include_cookbook 'git'
include_cookbook 'vim'
include_cookbook 'zsh'
include_cookbook 'tmux'
include_cookbook 'ruby'
include_cookbook 'golang'

ln '.vimperatorrc'
ln '.bash_profile'
ln 'bin'
